### ISSUE TITLE
[SUGGESTION] AimBot for like bows and stuff

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#136] opened 2021-12-06 10:37 UTC
Issue:
title.

Context:
useful for bow pvp

Environment: 
* What other clients do you run, PC setup, relevant servers?

Config:
* Attach any relevant parts of your config here.

**Comment by linustouchtips** [comment] 2021-12-06 17:05
Duplicate of #53

**Closed by linustouchtips** 2021-12-06 17:05 UTC
Labels: enhancement
